---
# tasks file for unzip

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: unzip

- name: Include distribution specific tasks
  include: "{{ ansible_distribution }}.yml"
  tags: unzip
